# Generated by Django 2.0.1 on 2018-01-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_centralizarii', models.DateField()),
                ('nr_uaturi_cad_fin', models.SmallIntegerField()),
                ('nr_sectoare_cad_fin', models.SmallIntegerField()),
                ('sup_carti_fun', models.DecimalField(decimal_places=4, max_digits=11)),
                ('nr_uaturi_in_lucru', models.SmallIntegerField()),
                ('nr_sc_in_lucru', models.SmallIntegerField()),
                ('nr_contracte_finantare', models.SmallIntegerField()),
                ('nr_contracte_servicii', models.SmallIntegerField()),
            ],
        ),
    ]
